- name: Installation du jdk8
  package: name=openjdk-8-jdk-headless state=present

- name: Telechargement de TomEE
  get_url:
    url: '{{tomee_url}}'
    dest: '{{tomee_home}}/apache-tomee-7.0.3-plus.tar.gz'
    group: tomee
    owner: tomee
 
 - name: Création du compte pour TomEE
  user:
    name: tomee
    shell: /bin/false
    system: yes
    home: '{{tomee_home}}'

- name: Création du dossier /opt/tomee
  file:
    path: /opt/tomee
    state: directory
    mode: 0755
    owner: tomee
    group: tomee
    
- name: Changer le propriétaire du dossier
    file: path=/opt/tomee owner=tomee group=tomee state=directory recurse=yes

- name : Décompression de l'archive
  unarchive:
    src: '{{tomee_home}}/apache-tomee-7.0.3-plus.tar.gz'
    dest: /opt/tomee/
    remote_src: True

- name: Création d'un TomEE systemd
  file: path="/etc/systemd/system/tomcat.service" state=touch
  
  - name: Ecriture d'un systemd
  copy:
    dest: /etc/systemd/system/tomee.service
    content: |
      [Unit]
      Description=Apache TomEE Web Application Container
      After=network.target

      [Service]
      Type=forking

      Environment=JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre/
      Environment=CATALINA_HOME=/opt/tomee/apache-tomee-plus-7.0.3
      Environment=CATALINA_BASE=/opt/tomee/apache-tomee-plus-7.0.3
      Environment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
      Environment='JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom'

      ExecStart=/opt/tomee/apache-tomee-plus-7.0.3/bin/startup.sh
      ExecStop=/opt/tomee/apache-tomee-plus-7.0.3/bin/shutdown.sh

      User=tomee
      Group=root
      RestartSec=10
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Lancement de TomEE au démarrage
  shell: sudo systemctl enable tomee.service


